### ISSUE TITLE
How to use fidelity API for stable diffusion provided by hugging face diffusers

### ISSUE THREAD

**Issue by rutuja1409** [toshas/torch-fidelity#59] opened 2024-07-16 20:34 UTC
Hello @toshas @mikeogezi @voletiv 

Thank you so much for the amazing work. 

I am working with unconditional image generation provided by hugging face diffusers. https://github.com/huggingface/diffusers/blob/main/examples/unconditional_image_generation/train_unconditional.py

Here how can I integrate torch fidelity API. It requires generator, so in case of hugging face diffusers, should I pass accelerator as there is no generator present. Can you please guide me?

wrapped_generator = torch_fidelity.GenerativeModelModuleWrapper(generator, 128, 'normal', 0)

Should I write the code like below?

unet = accelerator.unwrap_model(model)
pipeline = DDPMPipeline(
                    unet=unet,
                    scheduler=noise_scheduler,)
generator = torch.Generator(device=pipeline.device).manual_seed(0)

Thank you :)

**Comment by toshas** [comment] 2024-07-21 12:57
Hi there, `GenerativeModelModuleWrapper` is mainly designed for GANs, although it can be repurposed too. You would have to see how it supplies noise and wrap the diffusers pipeline accordingly. What would be more straightforward to do instead is this: 
1. Generate a set of images by the diffusers pipeline, dump them to disk in a folder, say `path_source`
2. The reference images should be available in another folder, `path_reference`. For FID computation, it is important that the number of images between source and reference is roughly the same and large enough (e.g., 50000)—refer to popular evaluation protocols.
3. Run torch-fidelity as a `fidelity` shell command from your environment and supply the two directory as input arguments. Once you are happy with the numbers, you can use the `calculate_metrics` method to skip having to call anything from the shell.

HTH! Since this issue is not a bug, I'm closing it, but feel free to respond here.

**Closed by toshas** 2024-07-21 12:57 UTC
